### ISSUE TITLE
Inherited methods do not behave properly.

### ISSUE THREAD

**Issue by theqabalist** [fluture-js/fluenture#6]
The inherited methods created by virtue of the line
`Fluenture.prototype = Object.create(Future.prototype)` are invoked when a fluenture variant of a future is utilized with libraries like ramda that preferentially dispatch to fantasy-land methods.

I'm not sure why this inheritance is here as it doesn't immediately seem to be useful? But perhaps I am missing something.  In order to avoid this you would have to write something like
```javascript
fluent(R.map(add(6), fluent(Future.resolve(5))))
```
which is quite unwieldy.  Is there any way to fix this issue?  It seems like in this case, you want ramda to dispatch to `map` not to `fantasy-land/map` which is not controllable by this library.

**Comment by Avaq** [comment]
>  Is there any way to fix this issue?

It should be easy to fix by overriding the fantasy-land methods on this lib with variants that return fluent Futures.

**Comment by theqabalist** [comment]
This is that I actually did in a fork. Would you like me to PR it for inclusion?

**Comment by Avaq** [comment]
That'd be cool, thank you! :)
